#!/bin/bash

###QCMD=/ifs/data/socci/Work/SGE/qCMD
QCMD=/home/mpirun/tools/qCMD
QRSH=/common/sge/bin/lx24-amd64/qrsh
HOLD_ID=$1

USER=$(/usr/bin/whoami)
if [ ! -d "/ifs/data/${USER}/tmp" ]; then
    mkdir /ifs/data/${USER}/tmp
fi
export TMPDIR=/ifs/data/${USER}/tmp
SEMAPHORE=$(mktemp -t QSYNC_XXXXXXXX)
echo SYNC $HOLD_ID >$SEMAPHORE
date >>$SEMAPHORE

TAG=qSync.${HOLD_ID} ##${SEMAPHORE##*/}
echo $TAG
sleep 2
while [ -e $SEMAPHORE ]; do
	cat $SEMAPHORE
	sleep 1
	echo "Holding for" $HOLD_ID, $SEMAPHORE
	$QRSH -now no -hold_jid $HOLD_ID -N $TAG /bin/rm $SEMAPHORE
	#echo "===="
	#cat $SEMAPHORE
	#echo "--"

done

